[project]
name = "dataretrieval-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "anthropic>=0.49.0",
    "dataretrieval>=1.0.11",
    "httpx>=0.28.1",
    "mcp[cli]>=1.3.0",
    "pandas>=2.2.3",
]
